version: "3.8"
services:
  dev-database:
    container_name: hhplus-lecture-dev-database
    build:
      context: ./database
    image: mysql:8.0.33
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=hhplus-lecture-dev-database
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/config/init-dev.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3302:3306"

  stage-database:
    container_name: hhplus-lecture-stage-database
    build:
      context: ./database
    image: mysql:8.0.33
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=hhplus-lecture-stage-database
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/config/init-stage.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3301:3306"
