spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:mysql://localhost:3306/study_calendar
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rene
    password: itiswhatitis
  main:
    web-application-type: none

logging:
  level:
    org:
      springframework:
        jdbc: TRACE
        transaction: DEBUG
        batch: DEBUG