server:
  port: 9000
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 3000
      min-spare: 1000

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mvc_webflux_jmeter_test
    username: root
    password: mysql1234
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: on
    hibernate:
      ddl-auto: create